title: Tucker Lucey # your name (or website title) here
logo: "C://Users/tucke/Downloads/GOPRO605_edited.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student at the University of Rhode Island 
  <br><br>
  Department of Natural Resources
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
